add: Update info if new django CMS version is available
django-cms/djangocms-admin-style pull request #474
Opened 2022-12-13 16:30 UTC by fsbraun

This PR modifies and automates user information if a new django cms version (minor or patch, **not** major) is available:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/16904477/207389013-522d0450-82e6-46f8-abe6-6fd041b64007.png">

This feature was available for a while but required a  curated version list on `django-cms.org`. Now, the version list on pypi.org is take for reference. 

Also, the (admittedly minimal) python test suite has been extended and testing take to Django up to 4.1 and Python 3.11.

2022-12-13 17:54 UTC, marksweb commented
@fsbraun i thought pre commit was complaining about the title, but turns out there's an isort failure.

2022-12-14 09:57 UTC, marksweb requested changes

2022-12-14 09:58 UTC, fsbraun commented on tests/requirements/django-3.2.txt
> +Django>=4.1,<4.2
Upsi.

2022-12-14 10:01 UTC, fsbraun commented on tests/requirements/django-3.2.txt
> +Django>=4.1,<4.2
Fixed. The file names were swapped. 🤦🏻‍♂️

2022-12-14 11:01 UTC, marksweb approved these changes

2022-12-14 11:02 UTC, merged