feat: Add RTL support to admin modal
django-cms/djangocms-admin-style pull request #525
Opened 2024-03-18 09:13 UTC by sakhawy

## Description

Added RTL support to cms-admin-modal

## Related resources

* #521

## Screenshots

![Screenshot from 2024-03-18 11-10-57](https://github.com/django-cms/djangocms-admin-style/assets/50373064/39e2acea-0bcc-47a4-b50a-7d311c7c9078)
![Screenshot from 2024-03-18 11-11-03](https://github.com/django-cms/djangocms-admin-style/assets/50373064/a3c6e396-cc97-482b-a3a8-884e3f5f5497)

## Checklist

* [ ] I have added or modified the tests when changing logic
* [X] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst)

2024-03-21 12:00 UTC, fsbraun commented
@sakhawy Are the buttons and header positioned correctly?

2024-03-21 12:06 UTC, sakhawy commented
Oh, I missed that! I'll adjust it, thanks!

2024-03-21 12:23 UTC, sakhawy commented
@fsbraun Should I make this adjustment from ``djangocms-admin-style``? Or would it better be a ``django-cms`` PR since the styling of ``cms-modal-title`` is in ``django-cms/cms/static/cms/sass/components/_modal.scss``?

2024-03-21 14:31 UTC, fsbraun commented
You're right, of course.

2024-03-22 18:17 UTC, fsbraun commented on djangocms_admin_style/sass/components/_forms.scss
>              float: left !important;
Couldn't that be `float: start`?

2024-03-22 18:18 UTC, fsbraun commented on djangocms_admin_style/sass/components/_modal.scss
>                      float: left;
```suggestion
                    float: start;
```

2024-03-22 18:18 UTC, fsbraun commented on djangocms_admin_style/sass/components/_modal.scss
>              float: left;
```suggestion
            float: start;
```

2024-03-22 18:19 UTC, fsbraun requested changes
I think you can use `float: start` and `float: end`...

2024-03-22 18:41 UTC, sakhawy commented
@fsbraun ``inline-start`` and ``inline-end`` are not supported on relatively older browsers (as recent as 2023): https://caniuse.com/mdn-css_properties_float_inline-start so, I wanted to be extra careful. Should I make the change?

2024-03-22 20:48 UTC, fsbraun approved these changes

2024-03-26 17:48 UTC, merged

2024-04-02 02:55 UTC, joshyu commented
@fsbraun , I think it's not a best practice to use too many `!important` in the CSS codes, which prevent us from customize those styes easily.

2024-04-02 07:00 UTC, fsbraun commented
@joshyu I fully agree. djangocms-admin-style is not a good example for this, but has gone down that road may years ago. Alas, I believe with a bit of work this is fixable in most cases since all admin pages have the class `djangocms-admin-style` added to them allowing to override other styles by using higher specificity. It would be great if someone addressed this.

As a simpler work-around, I have created my own `djangocms-simple-admin-style` project (available on pypi): It tries to keep as many original django styles as possible and to void `!important`... Downside: It only works on browsers supporting CSS nesting (https://caniuse.com/css-nesting)